name: PR feedback
on:
  pull_request:

jobs:
  clippy:
    strategy:
      matrix:
        include:
          - platform: macos
          - platform: ubuntu
          - platform: windows

    name: Clippy on ${{ matrix.platform }}
    runs-on: "${{ matrix.platform }}-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
         command: clippy

  fmt-check:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

  windows-console:
    name: Check windows-console feature compiles
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features windows-console
          # check to make sure it keeps compiling, but this is unsupported buggy code for now

  windows-tests-msrv:
    name: Check windows-10 tests compile on MSRV
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.51.0
          override: true
      - run: cd tests/win10; cargo check
